### ISSUE TITLE
Error message received when running online

### ISSUE THREAD

**Issue by HaoyeTang** [ReddeR1337/PUBG-Radar#14]
When I run the online BAT file I received the following error message:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\xxxxxxxx\AppData\Local\Temp\jna--821451814\jna3234054297770194833.dll: Can't find dependent libraries
        at java.base/java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.load0(Unknown Source)
        at java.base/java.lang.System.load(Unknown Source)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:851)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826)
        at com.sun.jna.Native.<clinit>(Native.java:140)
        at com.sun.jna.Pointer.<clinit>(Pointer.java:41)
        at com.sun.jna.ptr.PointerByReference.<init>(PointerByReference.java:28)
        at com.sun.jna.ptr.PointerByReference.<init>(PointerByReference.java:24)
        at org.pcap4j.core.Pcaps.findAllDevs(Pcaps.java:48)
        at pubg.radar.sniffer.Sniffer.<clinit>(Sniffer.kt:53)
        at pubg.radar.GameKt.main(Game.kt:56)
```

**Comment by nengbowan** [comment]
install a software called wpcap , it's a base library

**Comment by HaoyeTang** [comment]
The issue is resolved. It is not because wpcap, I installed it already. Got it fixed by installing VC++ and shits
