### ISSUE TITLE
ERROR! 

### ISSUE THREAD

**Issue by natrix5369** [ReddeR1337/PUBG-Radar#15]
Hi. I use Oracle VM VirtualBox.

After launching your radar error:

AL lib: (EE) ALCmmdevPlayback_open: Device init failed: 0x80070490
Exception in thread "main" java.lang.IllegalStateException: This function is not
 available.
        at org.lwjgl.system.Checks.checkFunctionAddress(Checks.java:94)
        at org.lwjgl.opengl.GL30.nglGenVertexArrays(GL30.java:2790)
        at org.lwjgl.opengl.GL30.glGenVertexArrays(GL30.java:2802)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3GL30.glGenVertexArrays(Lwjgl3G
L30.java:355)
        at com.badlogic.gdx.graphics.glutils.VertexBufferObjectWithVAO.createVAO
(VertexBufferObjectWithVAO.java:262)
        at com.badlogic.gdx.graphics.glutils.VertexBufferObjectWithVAO.<init>(Ve
rtexBufferObjectWithVAO.java:78)
        at com.badlogic.gdx.graphics.glutils.VertexBufferObjectWithVAO.<init>(Ve
rtexBufferObjectWithVAO.java:58)
        at com.badlogic.gdx.graphics.Mesh.<init>(Mesh.java:165)
        at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:101
)
        at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:78)

        at pubg.radar.ui.GLMap.create(GLMap.kt:305)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjg
l3Window.java:416)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.jav
a:364)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Applica
tion.java:136)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Appli
cation.java:110)
        at pubg.radar.ui.GLMap.show(GLMap.kt:112)
        at pubg.radar.GameKt.main(Game.kt:58)

**Comment by natrix5369** [comment]
![screenshot_5](https://user-images.githubusercontent.com/37199932/37187324-d63a49de-235a-11e8-83c3-7761b020592f.png)

**Comment by natrix5369** [comment]
Corrected. Created a virtual machine in vmvare
