### ISSUE TITLE
New build Exception in thread "main"

### ISSUE THREAD

**Issue by ryan19629** [ReddeR1337/PUBG-Radar#60]
Received this after trying to run online.bat or manual.bat, any ideas?

`Exception in thread "main" java.lang.ExceptionInInitializerError
        at pubgradar.GameKt.main(Game.kt:68)
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at pubgradar.Sniffer.<clinit>(Sniffer.kt:218)
        ... 1 more
`

**Comment by ReddeR1337** [comment]
invalid ip

**Comment by ryan19629** [comment]
I tried with the version last week, and it worked fine with, same settings for IP.

**Comment by ryan19629** [comment]
Received this one after it loaded though.

`AL lib: (EE) ALCmmdevPlayback_mixerProc: Failed to get padding: 0x88890004
Game over
Exception in thread "Thread-1" java.lang.IndexOutOfBoundsException
        at pubgradar.deserializer.Buffer.readBit(Buffer.kt:89)
        at pubgradar.deserializer.Buffer.readByte(Buffer.kt:97)
        at pubgradar.deserializer.Buffer.readIntPacked(Buffer.kt:139)
        at pubgradar.deserializer.PacketParserKt.proc_raw_packet(PacketParser.kt:68)
        at pubgradar.deserializer.PacketParserKt.proc_raw_packet(PacketParser.kt:52)
        at pubgradar.deserializer.PacketParserKt$parsePackets$1.invoke(PacketParser.kt:34)
        at pubgradar.deserializer.PacketParserKt$parsePackets$1.invoke(PacketParser.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)`

**Comment by ReddeR1337** [comment]
virtualbox ?
https://github.com/ReddeR1337/PUBG-Radar#vm
---------
https://github.com/ReddeR1337/PUBG-Radar#if-you-have-glfw_platform_error-try-this

**Comment by ryan19629** [comment]
No 2nd PC using VPN, and connecting via remote desktop. The only tweak I need to make is to run the .bat files as console rather than from the RDP session otherwise you get openGL issues.
