### ISSUE TITLE
ERROR OPEN GL

### ISSUE THREAD

**Issue by brunopayne** [ReddeR1337/PUBG-Radar#7]
[LWJGL] GLFW_API_UNAVAILABLE error
        Description : WGL: The driver does not appear to support OpenGL
        Stacktrace  :
                org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1235)
                org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1388)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:425)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:372)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:107)
                pubg.radar.ui.GLMap.show(GLMap.kt:99)
                pubg.radar.GameKt.main(Game.kt:52)
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't create window
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:428)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:372)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:107)
        at pubg.radar.ui.GLMap.show(GLMap.kt:99)
        at pubg.radar.GameKt.main(Game.kt:52)
AL lib: (EE) alc_cleanup: 1 device not closed

How fix this ? Hyper-V Machine

**Comment by ReddeR1337** [comment]
https://github.com/ReddeR1337/PUBG-Radar/issues/5
